name: flutter_boring
description: A new Flutter project.

environment:
    sdk: '>=3.0.5 <4.0.0'

dependencies:
    flutter:
        sdk: flutter

    cupertino_icons: ^1.0.2
    firebase_core: ^2.15.1
    cloud_firestore: ^4.9.0
    google_maps_flutter: ^2.2.3
    flutter_native_splash: ^2.3.2
    intl: ^0.18.0
    open_street_map_search_and_pick: ^0.1.0
    location: ^5.0.3
    flutter_swipe_detector: ^2.0.0
    url_launcher: ^6.1.14

flutter_native_splash:
    color: '#ffffff'
    image: 'assets/logo/boring.png'
    android: true
    ios: true

dev_dependencies:
    flutter_lints: ^2.0.3
    flutter_test:
        sdk: flutter
    flutter_launcher_icons: '^0.13.1'

flutter_launcher_icons:
    android: 'launcher_icon'
    ios: true
    image_path: 'assets/logo/boring.png'
    min_sdk_android: 21 # android min sdk min:16, default 21
    web:
        generate: true
        image_path: 'assets/logo/boring.png'
        background_color: '#hexcode'
        theme_color: '#hexcode'
    windows:
        generate: true
        image_path: 'assets/logo/boring.png'
        icon_size: 48 # min:48, max:256, default: 48
    macos:
        generate: true
        image_path: 'assets/logo/boring.png'

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
    # The following line ensures that the Material Icons font is
    # included with your application, so that you can use the icons in
    # the material Icons class.
    uses-material-design: true

    # To add assets to your application, add an assets section, like this:

    # To add assets to your application, add an assets section, like this:

    assets:
        - assets/images/ginting.jpg
        - assets/images/gideon.jpg
        - assets/images/taufik.jpg
        - assets/images/gideon2.jpg
        - assets/images/gor1.jpeg
        - assets/images/gor2.png
        - assets/images/jatiasih.jpeg
