name: flutter_boring
description: A new Flutter project.




environment:
    sdk: '>=3.0.5 <4.0.0'


dependencies:
    flutter:
        sdk: flutter
  
    cupertino_icons: ^1.0.2
    firebase_core: ^2.15.1
    cloud_firestore: ^4.9.0
    web_date_picker: ^1.0.0+3
    google_maps_flutter: ^2.5.0
    flutter_native_splash: ^2.3.2
    flutter_lints: ^2.0.3
    intl: ^0.17.0


dev_dependencies:
    flutter_test:
        sdk: flutter

flutter_native_splash:
color: "#42a5f5"
image: assets/images/gideon.jpg
android: true


   
   

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
    # The following line ensures that the Material Icons font is
    # included with your application, so that you can use the icons in
    # the material Icons class.
    uses-material-design: true

    # To add assets to your application, add an assets section, like this:

  # To add assets to your application, add an assets section, like this:

    assets:
    - assets/images/ginting.jpg
    - assets/images/gideon.jpg
    - assets/images/taufik.jpg
    - assets/images/gideon2.jpg
    - assets/images/gor1.jpeg
    - assets/images/gor2.png
    - assets/images/jatiasih.jpeg

   